version: '2'

services:
  herlan-cms:
    build: .
    command: gunicorn -b 0.0.0.0:8000 --access-logfile - --reload "herlan-cms.app:create_app()"
    environment:
      PYTHONUNBUFFERED: 'true'
    volumes:
      - '.:/herlan-cms'
    ports:
      - '8000:8000'

  postgres:
    image: 'postgres:9.5'
    environment:
      POSTGRES_USER: 'devuser'
      POSTGRES_PASSWORD: 'devpassword'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - '5433:5432'

volumes:
  postgres:
